### PR TITLE
GH #15 Added more try-except blocks for critical artifact calls

### PR DESCRIPTION
**Pull request by PatrickDRusk**
Now present around all getter/deriver/transformer calls.

### CODE REVIEW

**Comment by Ludovicus** [comment]
I like

**Comment by ethanrowe** [comment]
I believe this resolves #15, yes?

**Comment by ethanrowe** [comment]
Shoot.  @PatrickDRusk , you should resubmit this guy going into "develop" instead of into "master".

**Comment by ethanrowe** [comment]
Closing due to going to master.

**Comment by PatrickDRusk** [comment]
Frick, sorry about that.

**Pull request closed without merging**
